### ISSUE TITLE
show two of the same kind of fix

### ISSUE THREAD

**Issue by Reaper1063** [bernarma/propsense#7]
good day sir

thank you for this indicator (propsense book levels)

I have a question,  my indicator shows the last london and tokyo fix, can I put it of to only show the present fixes?

thank you in advance

**Comment by bernarma** [comment]
I'll update it over the weekend and expose an input parameter that will allow you to configure how many fixes you would like to show. Would that help?

**Comment by Reaper1063** [comment]
Yes that would be fantastic sir.

Thank you for your time, have a great weekend.

**Comment by bernarma** [comment]
I have updated the indicator and exposed a parameter to customise the number of fixes shown - defaults to 2. Let me know if it is all good and I'll close this out.

**Comment by Reaper1063** [comment]
Good morning sir

Thank you  this works excellent.

Have a great day
